---

commands: |
    echo Hello
    git status
    git pull origin master
    git checkout -b setup
    git status
    python -m venv environment-name
    echo created environment-name
    echo. >> .gitignore
    echo # Environments >> .gitignore
    echo environment-name/ >> .gitignore
    echo # Local workspace configs >> .gitignore
    echo .vscode/ >> .gitignore
    echo. >> .gitignore
    echo # Secrets files >> .gitignore
    echo secrets.txt >> .gitignore
    git pull
    git status
    git add .gitignore
    git status
    git commit -m "Add_environment_name_to_.gitignore"
    git status
    git push origin setup
    git status
    environment-name\\Scripts\\python.exe -m pip --version
    environment-name\\Scripts\\python.exe -m pip install -r requirements_dev.txt
    ren project_name\\project_name.py new_name.py
    ren project_name new_name
    ren tests\\test_project_name.py test_new_name.py
    ren .env1 .env
    black .
    git status
    git add *
    git status
    pre-commit install
    pre-commit run --all-files
    git status
    git add *
    git status
    git commit -m "Create_files_and_run_pre-commit"
    git status
    git add *
    git status
    git commit -m "Create_files_and_run_pre-commit"
    git status
    git push origin setup
    git status

substitutions:
  - sub: django_users
    loc:
      - repo-name
  - sub: uenv
    loc:
      - environment-name
  - sub: django_users
    loc:
      - new_name
